"""foreign key revision

Revision ID: 74ea14ed3545
Revises: 47d8a82edd46
Create Date: 2023-09-25 15:54:50.206418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ea14ed3545'
down_revision = '47d8a82edd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses-enrolled', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_courses-enrolled_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_courses-enrolled_course_id_courses'), 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses-enrolled', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_courses-enrolled_course_id_courses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_courses-enrolled_user_id_users'), type_='foreignkey')
        batch_op.drop_column('course_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
